name: ci 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: '9.6.4'
          cabal-version: "3.10.2.1"
          enable-stack: true
          stack-version: "2.15.1"
      - run: stack test
