name: ci 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - uses: actions/checkout@v2
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.6.4'
          cabal-version: "3.10.2.1"
          enable-stack: true
          stack-version: "2.15.1"
      - name: test
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_KEY_PUBLIC: ${{ secrets.SSH_KEY_PUBLIC }}
        run: |
          stack test
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - uses: actions/checkout@v2
      - uses: haskell-actions/run-ormolu@v15
        with:
          ormolu-version: '0.7.2.0' # cabal.config に合わせる
    
